# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.AdminMeta do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"pagination"
  ]

  @type t :: %__MODULE__{
    :"pagination" => Pagination
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.AdminMeta do
  import Thinkific.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"pagination", :struct, Thinkific.Model.AdminPagination, options)
  end
end
