# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.AdminPagination do
  @moduledoc """
  Pagination metadata
  """

  @derive [Poison.Encoder]
  defstruct [
    :"current_page",
    :"next_page",
    :"prev_page",
    :"total_pages",
    :"total_items",
    :"entries_info"
  ]

  @type t :: %__MODULE__{
    :"current_page" => float(),
    :"next_page" => float(),
    :"prev_page" => float(),
    :"total_pages" => float(),
    :"total_items" => float(),
    :"entries_info" => String.t
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.AdminPagination do
  def decode(value, _options) do
    value
  end
end
