# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.BulkCreateCouponRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"bulk_quantity_per_coupon",
    :"bulk_coupon_code_length",
    :"bulk_quantity"
  ]

  @type t :: %__MODULE__{
    :"bulk_quantity_per_coupon" => float(),
    :"bulk_coupon_code_length" => float(),
    :"bulk_quantity" => float()
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.BulkCreateCouponRequest do
  def decode(value, _options) do
    value
  end
end
