# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.ChapterResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"position",
    :"description",
    :"duration_in_seconds",
    :"content_ids"
  ]

  @type t :: %__MODULE__{
    :"id" => float(),
    :"name" => String.t,
    :"position" => float(),
    :"description" => String.t,
    :"duration_in_seconds" => float(),
    :"content_ids" => [float()]
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.ChapterResponse do
  def decode(value, _options) do
    value
  end
end
