# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.CollectionResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"description",
    :"slug",
    :"created_at",
    :"product_ids",
    :"default"
  ]

  @type t :: %__MODULE__{
    :"id" => float(),
    :"name" => String.t,
    :"description" => String.t,
    :"slug" => String.t,
    :"created_at" => DateTime.t,
    :"product_ids" => [float()],
    :"default" => boolean()
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.CollectionResponse do
  def decode(value, _options) do
    value
  end
end
