# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.ContentResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"position",
    :"chapter_id",
    :"contentable_type",
    :"free",
    :"take_url"
  ]

  @type t :: %__MODULE__{
    :"id" => float(),
    :"name" => String.t,
    :"position" => float(),
    :"chapter_id" => float(),
    :"contentable_type" => ContentableType,
    :"free" => boolean(),
    :"take_url" => String.t
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.ContentResponse do
  import Thinkific.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"contentable_type", :struct, Thinkific.Model.ContentableType, options)
  end
end
