# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.CreateBulkCouponResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"items"
  ]

  @type t :: %__MODULE__{
    :"items" => [CouponResponse]
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.CreateBulkCouponResponse do
  import Thinkific.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"items", :list, Thinkific.Model.CouponResponse, options)
  end
end
