# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.CreateUserRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"first_name",
    :"last_name",
    :"email",
    :"password",
    :"roles",
    :"bio",
    :"company",
    :"headline",
    :"affiliate_code",
    :"affiliate_commission",
    :"affiliate_commission_type",
    :"affiliate_payout_email",
    :"custom_profile_fields",
    :"skip_custom_fields_validation",
    :"send_welcome_email",
    :"external_id"
  ]

  @type t :: %__MODULE__{
    :"first_name" => String.t,
    :"last_name" => String.t,
    :"email" => String.t,
    :"password" => String.t,
    :"roles" => [Role],
    :"bio" => String.t,
    :"company" => String.t,
    :"headline" => String.t,
    :"affiliate_code" => String.t,
    :"affiliate_commission" => float(),
    :"affiliate_commission_type" => String.t,
    :"affiliate_payout_email" => String.t,
    :"custom_profile_fields" => [CustomProfileFieldRequest],
    :"skip_custom_fields_validation" => boolean(),
    :"send_welcome_email" => boolean(),
    :"external_id" => float()
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.CreateUserRequest do
  import Thinkific.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"roles", :list, Thinkific.Model.Role, options)
    |> deserialize(:"custom_profile_fields", :list, Thinkific.Model.CustomProfileFieldRequest, options)
  end
end
