# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.CreateEnrollmentRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"course_id",
    :"user_id",
    :"activated_at",
    :"expiry_date"
  ]

  @type t :: %__MODULE__{
    :"course_id" => float(),
    :"user_id" => float(),
    :"activated_at" => DateTime.t,
    :"expiry_date" => DateTime.t
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.CreateEnrollmentRequest do
  def decode(value, _options) do
    value
  end
end
