# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.CreateGroupUsersRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"user_id",
    :"group_names"
  ]

  @type t :: %__MODULE__{
    :"user_id" => float(),
    :"group_names" => [String.t]
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.CreateGroupUsersRequest do
  def decode(value, _options) do
    value
  end
end
