# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.CustomProfileFieldRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"value",
    :"custom_profile_field_definition_id"
  ]

  @type t :: %__MODULE__{
    :"value" => String.t,
    :"custom_profile_field_definition_id" => float()
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.CustomProfileFieldRequest do
  def decode(value, _options) do
    value
  end
end
