# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.CustomProfileField do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"value",
    :"label",
    :"custom_profile_field_definition_id"
  ]

  @type t :: %__MODULE__{
    :"id" => float(),
    :"value" => String.t,
    :"label" => String.t,
    :"custom_profile_field_definition_id" => float()
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.CustomProfileField do
  def decode(value, _options) do
    value
  end
end
