# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.DiscountType do
  @moduledoc """
  The type of discount. Must be either &#39;fixed&#39; or &#39;percentage&#39;.
  """

  @derive [Poison.Encoder]
  defstruct [

  ]

  @type t :: %__MODULE__{

  }
end

defimpl Poison.Decoder, for: Thinkific.Model.DiscountType do
  def decode(value, _options) do
    value
  end
end
