# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.EnrollmentResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"user_email",
    :"user_name",
    :"user_id",
    :"course_name",
    :"course_id",
    :"percentage_completed",
    :"expired",
    :"is_free_trial",
    :"completed",
    :"started_at",
    :"activated_at",
    :"completed_at",
    :"updated_at",
    :"expiry_date"
  ]

  @type t :: %__MODULE__{
    :"id" => float(),
    :"user_email" => String.t,
    :"user_name" => String.t,
    :"user_id" => float(),
    :"course_name" => String.t,
    :"course_id" => float(),
    :"percentage_completed" => float(),
    :"expired" => boolean(),
    :"is_free_trial" => boolean(),
    :"completed" => boolean(),
    :"started_at" => DateTime.t,
    :"activated_at" => DateTime.t,
    :"completed_at" => DateTime.t,
    :"updated_at" => DateTime.t,
    :"expiry_date" => DateTime.t
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.EnrollmentResponse do
  def decode(value, _options) do
    value
  end
end
