# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.ExternalOrdersResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id"
  ]

  @type t :: %__MODULE__{
    :"id" => float()
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.ExternalOrdersResponse do
  def decode(value, _options) do
    value
  end
end
