# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.ExternalOrderTransaction do
  @moduledoc """
  External Order Transaction
  """

  @derive [Poison.Encoder]
  defstruct [
    :"amount",
    :"currency",
    :"reference",
    :"action"
  ]

  @type t :: %__MODULE__{
    :"amount" => float(),
    :"currency" => String.t,
    :"reference" => String.t,
    :"action" => String.t
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.ExternalOrderTransaction do
  def decode(value, _options) do
    value
  end
end
