# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.GroupAddAnalystRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"user_ids"
  ]

  @type t :: %__MODULE__{
    :"user_ids" => [float()]
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.GroupAddAnalystRequest do
  def decode(value, _options) do
    value
  end
end
