# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.GroupResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"token",
    :"created_at"
  ]

  @type t :: %__MODULE__{
    :"id" => float(),
    :"name" => String.t,
    :"token" => String.t,
    :"created_at" => DateTime.t
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.GroupResponse do
  def decode(value, _options) do
    value
  end
end
