# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.InstructorRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"user_id",
    :"title",
    :"first_name",
    :"last_name",
    :"bio",
    :"slug",
    :"avatar_url",
    :"email"
  ]

  @type t :: %__MODULE__{
    :"user_id" => float(),
    :"title" => String.t,
    :"first_name" => String.t,
    :"last_name" => String.t,
    :"bio" => String.t,
    :"slug" => String.t,
    :"avatar_url" => String.t,
    :"email" => String.t
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.InstructorRequest do
  def decode(value, _options) do
    value
  end
end
