# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.OrderResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"user_id",
    :"user_email",
    :"user_name",
    :"product_name",
    :"product_id",
    :"amount_dollars",
    :"amount_cents",
    :"subscription",
    :"coupon_code",
    :"coupon_id",
    :"affiliate_referral_code",
    :"status",
    :"created at",
    :"id"
  ]

  @type t :: %__MODULE__{
    :"user_id" => float(),
    :"user_email" => String.t,
    :"user_name" => String.t,
    :"product_name" => String.t,
    :"product_id" => float(),
    :"amount_dollars" => float(),
    :"amount_cents" => float(),
    :"subscription" => boolean(),
    :"coupon_code" => String.t,
    :"coupon_id" => float(),
    :"affiliate_referral_code" => String.t,
    :"status" => String.t,
    :"created at" => String.t,
    :"id" => float()
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.OrderResponse do
  def decode(value, _options) do
    value
  end
end
