# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.PaymentType do
  @moduledoc """
  The type of payment. Must be one of &#39;free&#39;, &#39;one-time&#39;, &#39;subscription&#39;, or &#39;payment-plan&#39;.
  """

  @derive [Poison.Encoder]
  defstruct [

  ]

  @type t :: %__MODULE__{

  }
end

defimpl Poison.Decoder, for: Thinkific.Model.PaymentType do
  def decode(value, _options) do
    value
  end
end
