# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.ProductPublishRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"product_id",
    :"status",
    :"response_text",
    :"requesting_user_id",
    :"responding_user_id",
    :"completed_at",
    :"created_at",
    :"updated_at"
  ]

  @type t :: %__MODULE__{
    :"product_id" => float(),
    :"status" => String.t,
    :"response_text" => String.t,
    :"requesting_user_id" => float(),
    :"responding_user_id" => float(),
    :"completed_at" => String.t,
    :"created_at" => String.t,
    :"updated_at" => String.t
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.ProductPublishRequest do
  def decode(value, _options) do
    value
  end
end
