# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.TrialInterval do
  @moduledoc """
  The interval for the trial period. Must be one of &#39;day&#39; or &#39;month&#39;.
  """

  @derive [Poison.Encoder]
  defstruct [

  ]

  @type t :: %__MODULE__{

  }
end

defimpl Poison.Decoder, for: Thinkific.Model.TrialInterval do
  def decode(value, _options) do
    value
  end
end
