# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.UnprocessableEntityError do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"errors"
  ]

  @type t :: %__MODULE__{
    :"errors" => [ValidationError]
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.UnprocessableEntityError do
  import Thinkific.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"errors", :list, Thinkific.Model.ValidationError, options)
  end
end
