# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.UpdateCoupon do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"code",
    :"note",
    :"quantity_used",
    :"quantity"
  ]

  @type t :: %__MODULE__{
    :"code" => String.t,
    :"note" => String.t,
    :"quantity_used" => String.t,
    :"quantity" => float()
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.UpdateCoupon do
  def decode(value, _options) do
    value
  end
end
