# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.ValidationError do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"field_name"
  ]

  @type t :: %__MODULE__{
    :"field_name" => String.t
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.ValidationError do
  def decode(value, _options) do
    value
  end
end
