# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.WebhookRequest do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"topic",
    :"target_url"
  ]

  @type t :: %__MODULE__{
    :"topic" => String.t,
    :"target_url" => String.t
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.WebhookRequest do
  def decode(value, _options) do
    value
  end
end
