# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.WebhookResponse do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"topic",
    :"target_url",
    :"status",
    :"created_by",
    :"created_at",
    :"updated_at",
    :"updated_by"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"topic" => String.t,
    :"target_url" => String.t,
    :"status" => String.t,
    :"created_by" => float(),
    :"created_at" => DateTime.t,
    :"updated_at" => DateTime.t,
    :"updated_by" => float()
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.WebhookResponse do
  def decode(value, _options) do
    value
  end
end
