# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Model.WebhooksPagination do
  @moduledoc """
  Pagination metadata
  """

  @derive [Poison.Encoder]
  defstruct [
    :"has_next",
    :"next_page",
    :"page_items",
    :"total_items",
    :"total_pages"
  ]

  @type t :: %__MODULE__{
    :"has_next" => boolean(),
    :"next_page" => String.t,
    :"page_items" => float(),
    :"total_items" => float(),
    :"total_pages" => float()
  }
end

defimpl Poison.Decoder, for: Thinkific.Model.WebhooksPagination do
  def decode(value, _options) do
    value
  end
end
