# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Api.GroupUsers do
  @moduledoc """
  API calls for all endpoints tagged `GroupUsers`.
  """

  alias Thinkific.Connection
  import Thinkific.RequestBuilder


  @doc """
  createGroupUsers
  Create an existing User to existing Groups

  ## Parameters

  - connection (Thinkific.Connection): Connection to server
  - body (CreateGroupUsersRequest): Group Users attributes
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec create_group_users(Tesla.Env.client, Thinkific.Model.CreateGroupUsersRequest.t, keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def create_group_users(connection, body, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/group_users")
    |> add_param(:body, :"body", body)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end
end
