# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Api.ProductPublishRequest do
  @moduledoc """
  API calls for all endpoints tagged `ProductPublishRequest`.
  """

  alias Thinkific.Connection
  import Thinkific.RequestBuilder


  @doc """
  Approves Product Publish Request
  Approves the Product Publish Request identified by the provided id.

  ## Parameters

  - connection (Thinkific.Connection): Connection to server
  - id (float()): ID of the Product Publish Request in the form of an integer.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec approves_product_publish_request(Tesla.Env.client, float(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def approves_product_publish_request(connection, id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/product_publish_requests/#{id}/approve")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  Denies Product Publish Request
  Denies the Product Publish Request identified by the provided id.

  ## Parameters

  - connection (Thinkific.Connection): Connection to server
  - id (float()): ID of the Product Publish Request in the form of an integer.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %{}} on success
  {:error, info} on failure
  """
  @spec denies_product_publish_request(Tesla.Env.client, float(), keyword()) :: {:ok, nil} | {:error, Tesla.Env.t}
  def denies_product_publish_request(connection, id, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/product_publish_requests/#{id}/deny")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(false)
  end

  @doc """
  getProductPublishRequestByID
  Returns the Product Publish Request identified by the provided id.

  ## Parameters

  - connection (Thinkific.Connection): Connection to server
  - id (float()): ID of the Product Publish Request in the form of an integer.
  - opts (KeywordList): [optional] Optional parameters

  ## Returns

  {:ok, %Thinkific.Model.ProductPublishRequest{}} on success
  {:error, info} on failure
  """
  @spec get_product_publish_request_by_id(Tesla.Env.client, float(), keyword()) :: {:ok, Thinkific.Model.ProductPublishRequest.t} | {:error, Tesla.Env.t}
  def get_product_publish_request_by_id(connection, id, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/product_publish_requests/#{id}")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Thinkific.Model.ProductPublishRequest{})
  end

  @doc """
  getProductPublishRequests
  Returns a list of Product Publish Requests.

  ## Parameters

  - connection (Thinkific.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
    - :page (float()): The page within the collection to fetch
    - :limit (float()): The number of items to be returned

  ## Returns

  {:ok, %Thinkific.Model.GetProductPublishResponse{}} on success
  {:error, info} on failure
  """
  @spec get_product_publish_requests(Tesla.Env.client, keyword()) :: {:ok, Thinkific.Model.GetProductPublishResponse.t} | {:error, Tesla.Env.t}
  def get_product_publish_requests(connection, opts \\ []) do
    optional_params = %{
      :"page" => :query,
      :"limit" => :query
    }
    %{}
    |> method(:get)
    |> url("/product_publish_requests")
    |> add_optional_params(optional_params, opts)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> decode(%Thinkific.Model.GetProductPublishResponse{})
  end
end
