# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule Thinkific.Deserializer do
  @moduledoc """
  Helper functions for deserializing responses into models
  """

  @doc """
  Update the provided model with a deserialization of a nested value
  """
  @spec deserialize(struct(), :atom, :atom, struct(), keyword()) :: struct()
  def deserialize(model, field, :list, mod, [as: options_struct]) do
    model
    |> Map.update!(field, &(Poison.decode!(Poison.encode!(&1), Keyword.merge([as: options_struct], [as: [struct(mod)]]))))
  end
  def deserialize(model, field, :list, mod, %{as: options_struct}) do
    model
    |> Map.update!(field, &(Poison.decode!(Poison.encode!(&1), Map.merge(%{as: options_struct}, %{as: [struct(mod)]}))))
  end

  def deserialize(model, field, :struct, mod, [as: options_struct]) do
    model
    |> Map.update!(field, &(Poison.decode!(Poison.encode!(&1), Keyword.merge([as: options_struct], [as: struct(mod)]))))
  end
  def deserialize(model, field, :struct, mod, %{as: options_struct}) do
    model
    |> Map.update!(field, &(Poison.decode!(Poison.encode!(&1), Map.merge(options_struct, %{as: struct(mod)}))))
  end

  def deserialize(model, field, :map, mod, options) do
    model
    |> Map.update!(field, &(Map.new(&1, fn {key, val} -> {key, Poison.Decode.decode(val, Keyword.merge(options, [as: struct(mod)]))} end)))
  end
  def deserialize(model, field, :date, _, _options) do
    value = Map.get(model, field)
    case is_binary(value) do
      true -> case DateTime.from_iso8601(value) do
                {:ok, datetime, _offset} ->
                  Map.put(model, field, datetime)
                _ ->
                  model
              end
      false -> model
    end
  end
end
